[package]
name = "pt-dump-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-slice-cast = "1.2.1"
rayon = "1.5.3"
nc = "0.8.4"
memchr = "2.5.0"
colored = "2.0.0"
rand = "0.8.4"